# Form implementation generated from reading ui file 'c:\Users\User\OneDrive\Tesis TSU Informatica\Sistema de control de inventario\Qt designer\1.Inicio.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ventana_inicio(object):
    def setupUi(self, ventana_inicio):
        ventana_inicio.setObjectName("ventana_inicio")
        ventana_inicio.resize(1080, 720)
        ventana_inicio.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(parent=ventana_inicio)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_fondo = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_fondo.setStyleSheet("background-color: rgb(22, 22, 20);")
        self.frame_fondo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_fondo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_fondo.setObjectName("frame_fondo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_fondo)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superior = QtWidgets.QFrame(parent=self.frame_fondo)
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_superior.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:1, y2:0.5, stop:0 rgba(11, 38, 67, 184), stop: 1 rgba(150, 88, 240, 255));\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254); }\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:0.949, y2:0.545455, stop: 0 rgba(11, 38, 67, 184), stop:1 rgba(88, 240, 171, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout_2.setContentsMargins(0, 5, 10, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_iniciarsesion = QtWidgets.QPushButton(parent=self.frame_superior)
        self.pushButton_iniciarsesion.setMinimumSize(QtCore.QSize(126, 30))
        self.pushButton_iniciarsesion.setObjectName("pushButton_iniciarsesion")
        self.horizontalLayout.addWidget(self.pushButton_iniciarsesion)
        self.pushButton_Salir = QtWidgets.QPushButton(parent=self.frame_superior)
        self.pushButton_Salir.setMinimumSize(QtCore.QSize(126, 30))
        self.pushButton_Salir.setStyleSheet("QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.727273 rgba(142, 19, 16, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}")
        self.pushButton_Salir.setObjectName("pushButton_Salir")
        self.horizontalLayout.addWidget(self.pushButton_Salir)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(781, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.frame_superior)
        self.frame_inferior = QtWidgets.QFrame(parent=self.frame_fondo)
        self.frame_inferior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_inferior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_inferior.setObjectName("frame_inferior")
        self.verticalLayout_2.addWidget(self.frame_inferior)
        self.verticalLayout.addWidget(self.frame_fondo)
        ventana_inicio.setCentralWidget(self.centralwidget)

        self.retranslateUi(ventana_inicio)
        QtCore.QMetaObject.connectSlotsByName(ventana_inicio)

    def retranslateUi(self, ventana_inicio):
        _translate = QtCore.QCoreApplication.translate
        ventana_inicio.setWindowTitle(_translate("ventana_inicio", "Inicio"))
        self.pushButton_iniciarsesion.setText(_translate("ventana_inicio", "Iniciar Sesion"))
        self.pushButton_Salir.setText(_translate("ventana_inicio", "Salir"))
