# Form implementation generated from reading ui file 'c:\Users\User\OneDrive\Tesis TSU Informatica\Sistema de control de inventario\Qt designer\2.Login.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_login(object):
    def setupUi(self, Dialog_login):
        Dialog_login.setObjectName("Dialog_login")
        Dialog_login.resize(235, 140)
        Dialog_login.setMaximumSize(QtCore.QSize(235, 140))
        Dialog_login.setStyleSheet("background-color: rgb(22, 22, 26);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog_login)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=Dialog_login)
        self.frame.setStyleSheet("\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"SansSerif\";\n"
"color: rgb(255, 255, 254);\n"
"border: 2px solid rgb(114, 117, 126);}\n"
"\n"
"QLineEdit:hover{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"border: 2px solid rgb(44, 182, 125); }\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(1, 1, 1);\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"border: 2px solid rgb(127, 90, 240);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:1, y2:0.5, stop:0 rgba(11, 38, 67, 184), stop: 1 rgba(150, 88, 240, 255));\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254); }\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:0.949, y2:0.545455, stop: 0 rgba(11, 38, 67, 184), stop:1 rgba(88, 240, 171, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}\n"
"\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.pushButton_aceptar = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_aceptar.setMinimumSize(QtCore.QSize(110, 30))
        self.pushButton_aceptar.setStyleSheet("")
        self.pushButton_aceptar.setObjectName("pushButton_aceptar")
        self.gridLayout_2.addWidget(self.pushButton_aceptar, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 10, -1, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_usuario = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_usuario.setMinimumSize(QtCore.QSize(151, 20))
        self.lineEdit_usuario.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_usuario.setObjectName("lineEdit_usuario")
        self.verticalLayout.addWidget(self.lineEdit_usuario)
        self.lineEdit_clave = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_clave.setMinimumSize(QtCore.QSize(151, 20))
        self.lineEdit_clave.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_clave.setDragEnabled(False)
        self.lineEdit_clave.setObjectName("lineEdit_clave")
        self.verticalLayout.addWidget(self.lineEdit_clave)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Dialog_login)
        QtCore.QMetaObject.connectSlotsByName(Dialog_login)

    def retranslateUi(self, Dialog_login):
        _translate = QtCore.QCoreApplication.translate
        Dialog_login.setWindowTitle(_translate("Dialog_login", "Login"))
        self.pushButton_aceptar.setText(_translate("Dialog_login", "Aceptar"))
        self.lineEdit_usuario.setPlaceholderText(_translate("Dialog_login", "Usuario"))
        self.lineEdit_clave.setPlaceholderText(_translate("Dialog_login", "Clave"))
