# Form implementation generated from reading ui file 'c:\Users\User\OneDrive\Tesis TSU Informatica\Sistema de control de inventario\Qt designer\6.Reportes.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1080, 720))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1080, 720))
        self.centralwidget.setStyleSheet("background-color: rgb(22, 22, 20);\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superior = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_superior.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:1, y2:0.5, stop:0 rgba(11, 38, 67, 184), stop: 1 rgba(150, 88, 240, 255));\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254); }\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:0.949, y2:0.545455, stop: 0 rgba(11, 38, 67, 184), stop:1 rgba(88, 240, 171, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_stock = QtWidgets.QPushButton(parent=self.frame_superior)
        self.pushButton_stock.setMinimumSize(QtCore.QSize(126, 30))
        self.pushButton_stock.setStyleSheet("")
        self.pushButton_stock.setObjectName("pushButton_stock")
        self.horizontalLayout.addWidget(self.pushButton_stock)
        self.pushButton_Ventas = QtWidgets.QPushButton(parent=self.frame_superior)
        self.pushButton_Ventas.setMinimumSize(QtCore.QSize(126, 30))
        self.pushButton_Ventas.setStyleSheet("")
        self.pushButton_Ventas.setObjectName("pushButton_Ventas")
        self.horizontalLayout.addWidget(self.pushButton_Ventas)
        spacerItem = QtWidgets.QSpacerItem(245, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_regresar_rep = QtWidgets.QPushButton(parent=self.frame_superior)
        self.pushButton_regresar_rep.setMinimumSize(QtCore.QSize(126, 30))
        self.pushButton_regresar_rep.setStyleSheet("QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.727273 rgba(142, 19, 16, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}")
        self.pushButton_regresar_rep.setObjectName("pushButton_regresar_rep")
        self.horizontalLayout.addWidget(self.pushButton_regresar_rep)
        self.verticalLayout_2.addWidget(self.frame_superior)
        self.frame_inferior = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_inferior.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_inferior.setStyleSheet("QFrame{ \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLabel {\n"
"background-color: #000000ff;\n"
"}\n"
"\n"
"QTableWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    gridline-color: rgb(206, 0, 55);\n"
"font-size: 12px;\n"
"color: #000000;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"\n"
"background-color: rgb(0, 206, 151);\n"
"\n"
"border: 1px solid rgb(0, 0, 0);\n"
"\n"
"font-size: 12pt;\n"
"\n"
"}\n"
"\n"
"I\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"border: 1px solid rgb(0, 206, 151);\n"
"\n"
"}")
        self.frame_inferior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_inferior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_inferior.setObjectName("frame_inferior")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_inferior)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_inferior)
        self.stackedWidget.setMinimumSize(QtCore.QSize(1080, 720))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_stock = QtWidgets.QWidget()
        self.page_stock.setMinimumSize(QtCore.QSize(1080, 720))
        self.page_stock.setObjectName("page_stock")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_stock)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_stock = QtWidgets.QLabel(parent=self.page_stock)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        self.label_stock.setFont(font)
        self.label_stock.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_stock.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_stock.setObjectName("label_stock")
        self.verticalLayout_3.addWidget(self.label_stock)
        self.tableWidget_stock = QtWidgets.QTableWidget(parent=self.page_stock)
        self.tableWidget_stock.setMinimumSize(QtCore.QSize(0, 550))
        self.tableWidget_stock.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget_stock.setObjectName("tableWidget_stock")
        self.tableWidget_stock.setColumnCount(5)
        self.tableWidget_stock.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stock.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stock.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stock.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stock.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stock.setHorizontalHeaderItem(4, item)
        self.verticalLayout_3.addWidget(self.tableWidget_stock)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.pushButton_refrescar_stock_danados_2 = QtWidgets.QPushButton(parent=self.page_stock)
        self.pushButton_refrescar_stock_danados_2.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_refrescar_stock_danados_2.setStyleSheet("\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:1, y2:0.5, stop:0 rgba(11, 38, 67, 184), stop: 1 rgba(150, 88, 240, 255));\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254); }\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:0.949, y2:0.545455, stop: 0 rgba(11, 38, 67, 184), stop:1 rgba(88, 240, 171, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}")
        self.pushButton_refrescar_stock_danados_2.setObjectName("pushButton_refrescar_stock_danados_2")
        self.horizontalLayout_13.addWidget(self.pushButton_refrescar_stock_danados_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        spacerItem2 = QtWidgets.QSpacerItem(20, 73, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.stackedWidget.addWidget(self.page_stock)
        self.page_ventas = QtWidgets.QWidget()
        self.page_ventas.setStyleSheet("")
        self.page_ventas.setObjectName("page_ventas")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_ventas)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_stock_4 = QtWidgets.QLabel(parent=self.page_ventas)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        self.label_stock_4.setFont(font)
        self.label_stock_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_stock_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_stock_4.setObjectName("label_stock_4")
        self.verticalLayout_6.addWidget(self.label_stock_4)
        self.tableWidget_ventas = QtWidgets.QTableWidget(parent=self.page_ventas)
        self.tableWidget_ventas.setMinimumSize(QtCore.QSize(0, 550))
        self.tableWidget_ventas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_ventas.setObjectName("tableWidget_ventas")
        self.tableWidget_ventas.setColumnCount(5)
        self.tableWidget_ventas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ventas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ventas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ventas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ventas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ventas.setHorizontalHeaderItem(4, item)
        self.verticalLayout_6.addWidget(self.tableWidget_ventas)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.pushButton_refrescar_ventas = QtWidgets.QPushButton(parent=self.page_ventas)
        self.pushButton_refrescar_ventas.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_refrescar_ventas.setStyleSheet("\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:1, y2:0.5, stop:0 rgba(11, 38, 67, 184), stop: 1 rgba(150, 88, 240, 255));\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254); }\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:0.949, y2:0.545455, stop: 0 rgba(11, 38, 67, 184), stop:1 rgba(88, 240, 171, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}")
        self.pushButton_refrescar_ventas.setObjectName("pushButton_refrescar_ventas")
        self.horizontalLayout_12.addWidget(self.pushButton_refrescar_ventas)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        spacerItem4 = QtWidgets.QSpacerItem(20, 73, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.stackedWidget.addWidget(self.page_ventas)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.frame_inferior)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_stock.setText(_translate("MainWindow", "Stock"))
        self.pushButton_Ventas.setText(_translate("MainWindow", "Ventas"))
        self.pushButton_regresar_rep.setText(_translate("MainWindow", "Regresar"))
        self.label_stock.setText(_translate("MainWindow", "STOCK"))
        item = self.tableWidget_stock.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "SKU"))
        item = self.tableWidget_stock.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Codigo de Barra"))
        item = self.tableWidget_stock.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Descripción"))
        item = self.tableWidget_stock.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Precio $"))
        item = self.tableWidget_stock.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cantidad"))
        self.pushButton_refrescar_stock_danados_2.setText(_translate("MainWindow", "Actualizar"))
        self.label_stock_4.setText(_translate("MainWindow", "VENTAS"))
        item = self.tableWidget_ventas.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "SKU"))
        item = self.tableWidget_ventas.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Codigo de Barra"))
        item = self.tableWidget_ventas.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Descripción"))
        item = self.tableWidget_ventas.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Precio $"))
        item = self.tableWidget_ventas.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cantidad"))
        self.pushButton_refrescar_ventas.setText(_translate("MainWindow", "Actualizar"))
