# Form implementation generated from reading ui file 'c:\Users\User\OneDrive\Tesis TSU Informatica\Sistema de control de inventario\Qt designer\7.Ajustes_anadir_eliminar.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_ajustes(object):
    def setupUi(self, MainWindow_ajustes):
        MainWindow_ajustes.setObjectName("MainWindow_ajustes")
        MainWindow_ajustes.resize(1080, 720)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow_ajustes)
        self.centralwidget.setMinimumSize(QtCore.QSize(1080, 720))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_fondo = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_fondo.setMinimumSize(QtCore.QSize(1080, 720))
        self.frame_fondo.setStyleSheet("background-color: rgb(22, 22, 20);")
        self.frame_fondo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_fondo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_fondo.setObjectName("frame_fondo")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_fondo)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_superior = QtWidgets.QFrame(parent=self.frame_fondo)
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_superior.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:1, y2:0.5, stop:0 rgba(11, 38, 67, 184), stop: 1 rgba(150, 88, 240, 255));\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254); }\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:0.949, y2:0.545455, stop: 0 rgba(11, 38, 67, 184), stop:1 rgba(88, 240, 171, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout_6.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(245, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.pushButton_regresar_ajus = QtWidgets.QPushButton(parent=self.frame_superior)
        self.pushButton_regresar_ajus.setMinimumSize(QtCore.QSize(126, 30))
        self.pushButton_regresar_ajus.setStyleSheet("QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.727273 rgba(142, 19, 16, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}")
        self.pushButton_regresar_ajus.setObjectName("pushButton_regresar_ajus")
        self.horizontalLayout_6.addWidget(self.pushButton_regresar_ajus)
        self.verticalLayout_6.addWidget(self.frame_superior)
        self.frame_inferior = QtWidgets.QFrame(parent=self.frame_fondo)
        self.frame_inferior.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:1, y2:0.5, stop:0 rgba(11, 38, 67, 184), stop: 1 rgba(150, 88, 240, 255));\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254); }\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:0.949, y2:0.545455, stop: 0 rgba(11, 38, 67, 184), stop:1 rgba(88, 240, 171, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}")
        self.frame_inferior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_inferior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_inferior.setObjectName("frame_inferior")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_inferior)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 10)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem1 = QtWidgets.QSpacerItem(351, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.frame_busquedadeusuarios_4 = QtWidgets.QFrame(parent=self.frame_inferior)
        self.frame_busquedadeusuarios_4.setMinimumSize(QtCore.QSize(369, 606))
        self.frame_busquedadeusuarios_4.setMaximumSize(QtCore.QSize(369, 1000))
        self.frame_busquedadeusuarios_4.setStyleSheet("QLineEdit{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"SansSerif\";\n"
"color: rgb(255, 255, 254);\n"
"border: 2px solid rgb(114, 117, 126);}\n"
"\n"
"QLineEdit:hover{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"border: 2px solid rgb(44, 182, 125); }\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(1, 1, 1);\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"border: 2px solid rgb(127, 90, 240);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:1, y2:0.5, stop:0 rgba(11, 38, 67, 184), stop: 1 rgba(150, 88, 240, 255));\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254); }\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:0.949, y2:0.545455, stop: 0 rgba(11, 38, 67, 184), stop:1 rgba(88, 240, 171, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"SansSerif\";\n"
"color: rgb(255, 255, 254);\n"
"border: 2px solid rgb(114, 117, 126);}\n"
"\n"
"QComboBox:hover{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"border: 2px solid rgb(44, 182, 125); }\n"
"\n"
"QFrame{\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(84, 135, 255)\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.frame_busquedadeusuarios_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_busquedadeusuarios_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_busquedadeusuarios_4.setObjectName("frame_busquedadeusuarios_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_busquedadeusuarios_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_imagen_producto = QtWidgets.QFrame(parent=self.frame_busquedadeusuarios_4)
        self.frame_imagen_producto.setMinimumSize(QtCore.QSize(347, 300))
        self.frame_imagen_producto.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_imagen_producto.setStyleSheet("border-image: url(:/Producto/sticker-png-delivery-icon-product-icon.png);\n"
"background-color: rgb(255, 255, 255);")
        self.frame_imagen_producto.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_imagen_producto.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_imagen_producto.setObjectName("frame_imagen_producto")
        self.gridLayout_2.addWidget(self.frame_imagen_producto, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 4, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.label_actualizar_cantd = QtWidgets.QLabel(parent=self.frame_busquedadeusuarios_4)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        self.label_actualizar_cantd.setFont(font)
        self.label_actualizar_cantd.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 0px;\n"
"\n"
"border:0px;")
        self.label_actualizar_cantd.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_actualizar_cantd.setObjectName("label_actualizar_cantd")
        self.horizontalLayout_10.addWidget(self.label_actualizar_cantd)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.lineEdit_descrip_prod = QtWidgets.QLineEdit(parent=self.frame_busquedadeusuarios_4)
        self.lineEdit_descrip_prod.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_descrip_prod.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_descrip_prod.setObjectName("lineEdit_descrip_prod")
        self.gridLayout_2.addWidget(self.lineEdit_descrip_prod, 8, 0, 1, 1)
        self.lineEdit_cant_prod = QtWidgets.QLineEdit(parent=self.frame_busquedadeusuarios_4)
        self.lineEdit_cant_prod.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_cant_prod.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_cant_prod.setObjectName("lineEdit_cant_prod")
        self.gridLayout_2.addWidget(self.lineEdit_cant_prod, 9, 0, 1, 1)
        self.lineEdit_sku_buscar = QtWidgets.QLineEdit(parent=self.frame_busquedadeusuarios_4)
        self.lineEdit_sku_buscar.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_sku_buscar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_sku_buscar.setObjectName("lineEdit_sku_buscar")
        self.gridLayout_2.addWidget(self.lineEdit_sku_buscar, 5, 0, 1, 1)
        self.pushButton_actualizar_cant = QtWidgets.QPushButton(parent=self.frame_busquedadeusuarios_4)
        self.pushButton_actualizar_cant.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_actualizar_cant.setObjectName("pushButton_actualizar_cant")
        self.gridLayout_2.addWidget(self.pushButton_actualizar_cant, 10, 0, 1, 1)
        self.pushButton_buscar_sku = QtWidgets.QPushButton(parent=self.frame_busquedadeusuarios_4)
        self.pushButton_buscar_sku.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_buscar_sku.setObjectName("pushButton_buscar_sku")
        self.gridLayout_2.addWidget(self.pushButton_buscar_sku, 6, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 7, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 2, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 0, 0, 1, 1)
        self.horizontalLayout_11.addWidget(self.frame_busquedadeusuarios_4)
        spacerItem8 = QtWidgets.QSpacerItem(350, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.verticalLayout_6.addWidget(self.frame_inferior)
        self.verticalLayout.addWidget(self.frame_fondo)
        MainWindow_ajustes.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_ajustes)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_ajustes)

    def retranslateUi(self, MainWindow_ajustes):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_ajustes.setWindowTitle(_translate("MainWindow_ajustes", "MainWindow"))
        self.pushButton_regresar_ajus.setText(_translate("MainWindow_ajustes", "Regresar"))
        self.frame_imagen_producto.setWhatsThis(_translate("MainWindow_ajustes", "<html><head/><body><p><img src=\":/Producto/sticker-png-delivery-icon-product-icon.png\"/></p></body></html>"))
        self.label_actualizar_cantd.setText(_translate("MainWindow_ajustes", "ACTUALIZAR CANTIDAD DE PRODUCTOS"))
        self.lineEdit_descrip_prod.setPlaceholderText(_translate("MainWindow_ajustes", "Descripción"))
        self.lineEdit_cant_prod.setPlaceholderText(_translate("MainWindow_ajustes", "Cantidad"))
        self.lineEdit_sku_buscar.setPlaceholderText(_translate("MainWindow_ajustes", "SKU"))
        self.pushButton_actualizar_cant.setText(_translate("MainWindow_ajustes", "Actualizar"))
        self.pushButton_buscar_sku.setText(_translate("MainWindow_ajustes", "Buscar"))
