# Form implementation generated from reading ui file 'c:\Users\User\OneDrive\Tesis TSU Informatica\Sistema de control de inventario\Proyecto_teg\4.Gestion_de_usuarios.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_gestiondeusuarios(object):
    def setupUi(self, MainWindow_gestiondeusuarios):
        MainWindow_gestiondeusuarios.setObjectName("MainWindow_gestiondeusuarios")
        MainWindow_gestiondeusuarios.resize(1080, 720)
        MainWindow_gestiondeusuarios.setMinimumSize(QtCore.QSize(1080, 720))
        MainWindow_gestiondeusuarios.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        MainWindow_gestiondeusuarios.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow_gestiondeusuarios)
        self.centralwidget.setMinimumSize(QtCore.QSize(1080, 720))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_fondo = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_fondo.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_fondo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_fondo.setStyleSheet("background-color: rgb(22, 22, 20);\n"
"\n"
"\n"
"")
        self.frame_fondo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_fondo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_fondo.setObjectName("frame_fondo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_fondo)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superior = QtWidgets.QFrame(parent=self.frame_fondo)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_superior.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:1, y2:0.5, stop:0 rgba(11, 38, 67, 184), stop: 1 rgba(150, 88, 240, 255));\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254); }\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:0.949, y2:0.545455, stop: 0 rgba(11, 38, 67, 184), stop:1 rgba(88, 240, 171, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_usuarios = QtWidgets.QPushButton(parent=self.frame_superior)
        self.pushButton_usuarios.setMinimumSize(QtCore.QSize(126, 30))
        self.pushButton_usuarios.setStyleSheet("")
        self.pushButton_usuarios.setObjectName("pushButton_usuarios")
        self.horizontalLayout.addWidget(self.pushButton_usuarios)
        self.pushButton_anadir = QtWidgets.QPushButton(parent=self.frame_superior)
        self.pushButton_anadir.setMinimumSize(QtCore.QSize(126, 30))
        self.pushButton_anadir.setStyleSheet("")
        self.pushButton_anadir.setObjectName("pushButton_anadir")
        self.horizontalLayout.addWidget(self.pushButton_anadir)
        self.pushButton_actualizar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.pushButton_actualizar.setMinimumSize(QtCore.QSize(126, 30))
        self.pushButton_actualizar.setStyleSheet("")
        self.pushButton_actualizar.setObjectName("pushButton_actualizar")
        self.horizontalLayout.addWidget(self.pushButton_actualizar)
        self.pushButton_eliminar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.pushButton_eliminar.setMinimumSize(QtCore.QSize(126, 30))
        self.pushButton_eliminar.setStyleSheet("")
        self.pushButton_eliminar.setObjectName("pushButton_eliminar")
        self.horizontalLayout.addWidget(self.pushButton_eliminar)
        spacerItem = QtWidgets.QSpacerItem(245, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_regresar_gestion = QtWidgets.QPushButton(parent=self.frame_superior)
        self.pushButton_regresar_gestion.setMinimumSize(QtCore.QSize(126, 30))
        self.pushButton_regresar_gestion.setStyleSheet("QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.727273 rgba(142, 19, 16, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}")
        self.pushButton_regresar_gestion.setObjectName("pushButton_regresar_gestion")
        self.horizontalLayout.addWidget(self.pushButton_regresar_gestion)
        self.verticalLayout_2.addWidget(self.frame_superior)
        self.frame_inferior = QtWidgets.QFrame(parent=self.frame_fondo)
        self.frame_inferior.setMinimumSize(QtCore.QSize(1080, 720))
        self.frame_inferior.setMaximumSize(QtCore.QSize(16777215, 720))
        self.frame_inferior.setStyleSheet("QFrame{ \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLabel {\n"
"background-color: #000000ff;\n"
"}\n"
"\n"
"QTableWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    gridline-color: rgb(206, 0, 55);\n"
"font-size: 12px;\n"
"color: #000000;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"\n"
"background-color: rgb(0, 206, 151);\n"
"\n"
"border: 1px solid rgb(0, 0, 0);\n"
"\n"
"font-size: 12pt;\n"
"\n"
"}\n"
"\n"
"I\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"border: 1px solid rgb(0, 206, 151);\n"
"\n"
"}")
        self.frame_inferior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_inferior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_inferior.setObjectName("frame_inferior")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_inferior)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_inferior)
        self.stackedWidget.setMinimumSize(QtCore.QSize(1080, 720))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_usuarios = QtWidgets.QWidget()
        self.page_usuarios.setObjectName("page_usuarios")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_usuarios)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_usuarios = QtWidgets.QLabel(parent=self.page_usuarios)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        self.label_usuarios.setFont(font)
        self.label_usuarios.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_usuarios.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_usuarios.setObjectName("label_usuarios")
        self.verticalLayout_3.addWidget(self.label_usuarios)
        self.tableWidget_usuarios = QtWidgets.QTableWidget(parent=self.page_usuarios)
        self.tableWidget_usuarios.setMinimumSize(QtCore.QSize(0, 570))
        self.tableWidget_usuarios.setObjectName("tableWidget_usuarios")
        self.tableWidget_usuarios.setColumnCount(7)
        self.tableWidget_usuarios.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_usuarios.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_usuarios.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_usuarios.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_usuarios.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_usuarios.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_usuarios.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_usuarios.setHorizontalHeaderItem(6, item)
        self.verticalLayout_3.addWidget(self.tableWidget_usuarios)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_refrescar = QtWidgets.QPushButton(parent=self.page_usuarios)
        self.pushButton_refrescar.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_refrescar.setStyleSheet("\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:1, y2:0.5, stop:0 rgba(11, 38, 67, 184), stop: 1 rgba(150, 88, 240, 255));\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254); }\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:0.949, y2:0.545455, stop: 0 rgba(11, 38, 67, 184), stop:1 rgba(88, 240, 171, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}")
        self.pushButton_refrescar.setObjectName("pushButton_refrescar")
        self.horizontalLayout_2.addWidget(self.pushButton_refrescar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.stackedWidget.addWidget(self.page_usuarios)
        self.page_actualizar = QtWidgets.QWidget()
        self.page_actualizar.setStyleSheet("QFrame{\n"
"background-color: #0000000ff;\n"
"}")
        self.page_actualizar.setObjectName("page_actualizar")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_actualizar)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(349, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.frame_actualizardatosdeusuarios = QtWidgets.QFrame(parent=self.page_actualizar)
        self.frame_actualizardatosdeusuarios.setEnabled(True)
        self.frame_actualizardatosdeusuarios.setMinimumSize(QtCore.QSize(370, 640))
        self.frame_actualizardatosdeusuarios.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_actualizardatosdeusuarios.setStyleSheet("QLineEdit{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"SansSerif\";\n"
"color: rgb(255, 255, 254);\n"
"border: 2px solid rgb(114, 117, 126);}\n"
"\n"
"QLineEdit:hover{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"border: 2px solid rgb(44, 182, 125); }\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(1, 1, 1);\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"border: 2px solid rgb(127, 90, 240);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:1, y2:0.5, stop:0 rgba(11, 38, 67, 184), stop: 1 rgba(150, 88, 240, 255));\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254); }\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:0.949, y2:0.545455, stop: 0 rgba(11, 38, 67, 184), stop:1 rgba(88, 240, 171, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"SansSerif\";\n"
"color: rgb(255, 255, 254);\n"
"border: 2px solid rgb(114, 117, 126);}\n"
"\n"
"QComboBox:hover{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"border: 2px solid rgb(44, 182, 125); }\n"
"\n"
"QFrame{\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(84, 135, 255)\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.frame_actualizardatosdeusuarios.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_actualizardatosdeusuarios.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_actualizardatosdeusuarios.setObjectName("frame_actualizardatosdeusuarios")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_actualizardatosdeusuarios)
        self.verticalLayout_4.setContentsMargins(10, 10, -1, 50)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_actualizarusuarios = QtWidgets.QLabel(parent=self.frame_actualizardatosdeusuarios)
        self.label_actualizarusuarios.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        self.label_actualizarusuarios.setFont(font)
        self.label_actualizarusuarios.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 0px;\n"
"\n"
"border:0px;")
        self.label_actualizarusuarios.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_actualizarusuarios.setObjectName("label_actualizarusuarios")
        self.verticalLayout_4.addWidget(self.label_actualizarusuarios)
        self.label_imagnedeusuario = QtWidgets.QLabel(parent=self.frame_actualizardatosdeusuarios)
        self.label_imagnedeusuario.setMinimumSize(QtCore.QSize(200, 200))
        self.label_imagnedeusuario.setWhatsThis("")
        self.label_imagnedeusuario.setStyleSheet("border-image: url(:/Usuario/6326055.png);")
        self.label_imagnedeusuario.setText("")
        self.label_imagnedeusuario.setObjectName("label_imagnedeusuario")
        self.verticalLayout_4.addWidget(self.label_imagnedeusuario)
        self.lineEdit_cedulabuscar_actualizarusuarios = QtWidgets.QLineEdit(parent=self.frame_actualizardatosdeusuarios)
        self.lineEdit_cedulabuscar_actualizarusuarios.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_cedulabuscar_actualizarusuarios.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_cedulabuscar_actualizarusuarios.setObjectName("lineEdit_cedulabuscar_actualizarusuarios")
        self.verticalLayout_4.addWidget(self.lineEdit_cedulabuscar_actualizarusuarios)
        self.pushButton_buscar_usu = QtWidgets.QPushButton(parent=self.frame_actualizardatosdeusuarios)
        self.pushButton_buscar_usu.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_buscar_usu.setObjectName("pushButton_buscar_usu")
        self.verticalLayout_4.addWidget(self.pushButton_buscar_usu)
        self.lineEdit_nombre_actualizarusuarios = QtWidgets.QLineEdit(parent=self.frame_actualizardatosdeusuarios)
        self.lineEdit_nombre_actualizarusuarios.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_nombre_actualizarusuarios.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_nombre_actualizarusuarios.setObjectName("lineEdit_nombre_actualizarusuarios")
        self.verticalLayout_4.addWidget(self.lineEdit_nombre_actualizarusuarios)
        self.lineEdit_apellido_actualizarusuarios = QtWidgets.QLineEdit(parent=self.frame_actualizardatosdeusuarios)
        self.lineEdit_apellido_actualizarusuarios.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_apellido_actualizarusuarios.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_apellido_actualizarusuarios.setObjectName("lineEdit_apellido_actualizarusuarios")
        self.verticalLayout_4.addWidget(self.lineEdit_apellido_actualizarusuarios)
        self.lineEdit_telefono_actualizarusuarios = QtWidgets.QLineEdit(parent=self.frame_actualizardatosdeusuarios)
        self.lineEdit_telefono_actualizarusuarios.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_telefono_actualizarusuarios.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_telefono_actualizarusuarios.setObjectName("lineEdit_telefono_actualizarusuarios")
        self.verticalLayout_4.addWidget(self.lineEdit_telefono_actualizarusuarios)
        self.lineEdit_usuario_actualizarusuarios = QtWidgets.QLineEdit(parent=self.frame_actualizardatosdeusuarios)
        self.lineEdit_usuario_actualizarusuarios.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_usuario_actualizarusuarios.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_usuario_actualizarusuarios.setObjectName("lineEdit_usuario_actualizarusuarios")
        self.verticalLayout_4.addWidget(self.lineEdit_usuario_actualizarusuarios)
        self.lineEdit_clave_actualizarusuarios = QtWidgets.QLineEdit(parent=self.frame_actualizardatosdeusuarios)
        self.lineEdit_clave_actualizarusuarios.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_clave_actualizarusuarios.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_clave_actualizarusuarios.setObjectName("lineEdit_clave_actualizarusuarios")
        self.verticalLayout_4.addWidget(self.lineEdit_clave_actualizarusuarios)
        self.comboBox_permiso_actualizarusuarios = QtWidgets.QComboBox(parent=self.frame_actualizardatosdeusuarios)
        self.comboBox_permiso_actualizarusuarios.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_permiso_actualizarusuarios.setStyleSheet("color: rgb(255, 255, 255);")
        self.comboBox_permiso_actualizarusuarios.setMaxCount(2)
        self.comboBox_permiso_actualizarusuarios.setObjectName("comboBox_permiso_actualizarusuarios")
        self.comboBox_permiso_actualizarusuarios.addItem("")
        self.comboBox_permiso_actualizarusuarios.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_permiso_actualizarusuarios)
        self.pushButton_actualizarusuarios = QtWidgets.QPushButton(parent=self.frame_actualizardatosdeusuarios)
        self.pushButton_actualizarusuarios.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_actualizarusuarios.setObjectName("pushButton_actualizarusuarios")
        self.verticalLayout_4.addWidget(self.pushButton_actualizarusuarios)
        self.horizontalLayout_5.addWidget(self.frame_actualizardatosdeusuarios)
        spacerItem4 = QtWidgets.QSpacerItem(348, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.stackedWidget.addWidget(self.page_actualizar)
        self.page_eliminar = QtWidgets.QWidget()
        self.page_eliminar.setStyleSheet("QFrame{\n"
"background-color: #0000000ff;\n"
"}")
        self.page_eliminar.setObjectName("page_eliminar")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.page_eliminar)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem5 = QtWidgets.QSpacerItem(263, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.frame_busquedadeusuarios_3 = QtWidgets.QFrame(parent=self.page_eliminar)
        self.frame_busquedadeusuarios_3.setMinimumSize(QtCore.QSize(541, 651))
        self.frame_busquedadeusuarios_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_busquedadeusuarios_3.setStyleSheet("QLineEdit{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"SansSerif\";\n"
"color: rgb(255, 255, 254);\n"
"border: 2px solid rgb(114, 117, 126);}\n"
"\n"
"QLineEdit:hover{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"border: 2px solid rgb(44, 182, 125); }\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(1, 1, 1);\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"border: 2px solid rgb(127, 90, 240);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:1, y2:0.5, stop:0 rgba(11, 38, 67, 184), stop: 1 rgba(150, 88, 240, 255));\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254); }\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:0.949, y2:0.545455, stop: 0 rgba(11, 38, 67, 184), stop:1 rgba(88, 240, 171, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"SansSerif\";\n"
"color: rgb(255, 255, 254);\n"
"border: 2px solid rgb(114, 117, 126);}\n"
"\n"
"QComboBox:hover{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"border: 2px solid rgb(44, 182, 125); }\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QFrame{\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(225, 85, 88)\n"
"}\n"
"")
        self.frame_busquedadeusuarios_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_busquedadeusuarios_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_busquedadeusuarios_3.setObjectName("frame_busquedadeusuarios_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_busquedadeusuarios_3)
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 50)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(77, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 1, 0, 1, 1)
        self.label_imagnedeusuario_2 = QtWidgets.QLabel(parent=self.frame_busquedadeusuarios_3)
        self.label_imagnedeusuario_2.setMinimumSize(QtCore.QSize(347, 280))
        self.label_imagnedeusuario_2.setStyleSheet("border-image: url(:/Usuario/6326055.png);")
        self.label_imagnedeusuario_2.setText("")
        self.label_imagnedeusuario_2.setObjectName("label_imagnedeusuario_2")
        self.gridLayout_2.addWidget(self.label_imagnedeusuario_2, 1, 1, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(77, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 3, 1, 1)
        self.lineEdit_cedulabuscar_eliminar = QtWidgets.QLineEdit(parent=self.frame_busquedadeusuarios_3)
        self.lineEdit_cedulabuscar_eliminar.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_cedulabuscar_eliminar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_cedulabuscar_eliminar.setObjectName("lineEdit_cedulabuscar_eliminar")
        self.gridLayout_2.addWidget(self.lineEdit_cedulabuscar_eliminar, 2, 0, 1, 4)
        self.pushButton_buscar_eliminar = QtWidgets.QPushButton(parent=self.frame_busquedadeusuarios_3)
        self.pushButton_buscar_eliminar.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_buscar_eliminar.setObjectName("pushButton_buscar_eliminar")
        self.gridLayout_2.addWidget(self.pushButton_buscar_eliminar, 3, 0, 1, 4)
        self.tableWidget_eliminar = QtWidgets.QTableWidget(parent=self.frame_busquedadeusuarios_3)
        self.tableWidget_eliminar.setStyleSheet("QFrame{ \n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 0px;\n"
"}\n"
"\n"
"QLabel {\n"
"background-color: #000000ff;\n"
"}\n"
"")
        self.tableWidget_eliminar.setObjectName("tableWidget_eliminar")
        self.tableWidget_eliminar.setColumnCount(7)
        self.tableWidget_eliminar.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_eliminar.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_eliminar.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_eliminar.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_eliminar.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_eliminar.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_eliminar.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_eliminar.setHorizontalHeaderItem(6, item)
        self.gridLayout_2.addWidget(self.tableWidget_eliminar, 4, 0, 1, 4)
        self.pushButton_eliminar_eliminar = QtWidgets.QPushButton(parent=self.frame_busquedadeusuarios_3)
        self.pushButton_eliminar_eliminar.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_eliminar_eliminar.setStyleSheet("QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.727273 rgba(142, 19, 16, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}")
        self.pushButton_eliminar_eliminar.setObjectName("pushButton_eliminar_eliminar")
        self.gridLayout_2.addWidget(self.pushButton_eliminar_eliminar, 5, 0, 1, 4)
        self.label_eliminarusuarios = QtWidgets.QLabel(parent=self.frame_busquedadeusuarios_3)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        self.label_eliminarusuarios.setFont(font)
        self.label_eliminarusuarios.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 0px;\n"
"\n"
"border:0px;")
        self.label_eliminarusuarios.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_eliminarusuarios.setObjectName("label_eliminarusuarios")
        self.gridLayout_2.addWidget(self.label_eliminarusuarios, 0, 0, 1, 4)
        self.horizontalLayout_7.addWidget(self.frame_busquedadeusuarios_3)
        spacerItem8 = QtWidgets.QSpacerItem(262, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.stackedWidget.addWidget(self.page_eliminar)
        self.page_anadir = QtWidgets.QWidget()
        self.page_anadir.setStyleSheet("QFrame{\n"
"background-color: #0000000ff;\n"
"}")
        self.page_anadir.setObjectName("page_anadir")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page_anadir)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem9 = QtWidgets.QSpacerItem(261, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.frame_registrodeusuarios = QtWidgets.QFrame(parent=self.page_anadir)
        self.frame_registrodeusuarios.setMinimumSize(QtCore.QSize(1, 1))
        self.frame_registrodeusuarios.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_registrodeusuarios.setStyleSheet("QLineEdit{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"SansSerif\";\n"
"color: rgb(255, 255, 254);\n"
"border: 2px solid rgb(114, 117, 126);}\n"
"\n"
"QLineEdit:hover{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"border: 2px solid rgb(44, 182, 125); }\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(1, 1, 1);\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"border: 2px solid rgb(127, 90, 240);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:1, y2:0.5, stop:0 rgba(11, 38, 67, 184), stop: 1 rgba(150, 88, 240, 255));\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254); }\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:0.949, y2:0.545455, stop: 0 rgba(11, 38, 67, 184), stop:1 rgba(88, 240, 171, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"SansSerif\";\n"
"color: rgb(255, 255, 254);\n"
"border: 2px solid rgb(114, 117, 126);}\n"
"\n"
"QComboBox:hover{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"border: 2px solid rgb(44, 182, 125); }\n"
"\n"
"QFrame{\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(119, 255, 119)\n"
"}\n"
"\n"
"\n"
"")
        self.frame_registrodeusuarios.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_registrodeusuarios.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_registrodeusuarios.setObjectName("frame_registrodeusuarios")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_registrodeusuarios)
        self.gridLayout.setContentsMargins(-1, -1, -1, 25)
        self.gridLayout.setObjectName("gridLayout")
        self.label_imagendeusuarios_1 = QtWidgets.QLabel(parent=self.frame_registrodeusuarios)
        self.label_imagendeusuarios_1.setMinimumSize(QtCore.QSize(77, 280))
        self.label_imagendeusuarios_1.setStyleSheet("border-image: url(:/Usuario/6326055.png);")
        self.label_imagendeusuarios_1.setText("")
        self.label_imagendeusuarios_1.setObjectName("label_imagendeusuarios_1")
        self.gridLayout.addWidget(self.label_imagendeusuarios_1, 1, 0, 1, 2)
        self.lineEdit_clave_registrodeusuario = QtWidgets.QLineEdit(parent=self.frame_registrodeusuarios)
        self.lineEdit_clave_registrodeusuario.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_clave_registrodeusuario.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_clave_registrodeusuario.setObjectName("lineEdit_clave_registrodeusuario")
        self.gridLayout.addWidget(self.lineEdit_clave_registrodeusuario, 9, 1, 1, 1)
        self.comboBox_permiso = QtWidgets.QComboBox(parent=self.frame_registrodeusuarios)
        self.comboBox_permiso.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_permiso.setMaxCount(2)
        self.comboBox_permiso.setObjectName("comboBox_permiso")
        self.comboBox_permiso.addItem("")
        self.comboBox_permiso.addItem("")
        self.gridLayout.addWidget(self.comboBox_permiso, 10, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_limpiar_registrodeusuario = QtWidgets.QPushButton(parent=self.frame_registrodeusuarios)
        self.pushButton_limpiar_registrodeusuario.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_limpiar_registrodeusuario.setStyleSheet("QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.727273 rgba(142, 19, 16, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}")
        self.pushButton_limpiar_registrodeusuario.setObjectName("pushButton_limpiar_registrodeusuario")
        self.horizontalLayout_3.addWidget(self.pushButton_limpiar_registrodeusuario)
        self.pushButton_guardar_registrodeusuario = QtWidgets.QPushButton(parent=self.frame_registrodeusuarios)
        self.pushButton_guardar_registrodeusuario.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_guardar_registrodeusuario.setObjectName("pushButton_guardar_registrodeusuario")
        self.horizontalLayout_3.addWidget(self.pushButton_guardar_registrodeusuario)
        self.gridLayout.addLayout(self.horizontalLayout_3, 11, 0, 1, 2)
        self.label_registrodeusuario = QtWidgets.QLabel(parent=self.frame_registrodeusuarios)
        self.label_registrodeusuario.setMinimumSize(QtCore.QSize(500, 40))
        self.label_registrodeusuario.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        self.label_registrodeusuario.setFont(font)
        self.label_registrodeusuario.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 0px;\n"
"\n"
"border:0px;")
        self.label_registrodeusuario.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_registrodeusuario.setObjectName("label_registrodeusuario")
        self.gridLayout.addWidget(self.label_registrodeusuario, 0, 0, 1, 2)
        self.lineEdit_telefono_registrodeusuario = QtWidgets.QLineEdit(parent=self.frame_registrodeusuarios)
        self.lineEdit_telefono_registrodeusuario.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_telefono_registrodeusuario.setInputMask("")
        self.lineEdit_telefono_registrodeusuario.setText("")
        self.lineEdit_telefono_registrodeusuario.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_telefono_registrodeusuario.setObjectName("lineEdit_telefono_registrodeusuario")
        self.gridLayout.addWidget(self.lineEdit_telefono_registrodeusuario, 7, 0, 1, 2)
        self.lineEdit_usuario_registrodeusuario = QtWidgets.QLineEdit(parent=self.frame_registrodeusuarios)
        self.lineEdit_usuario_registrodeusuario.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_usuario_registrodeusuario.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_usuario_registrodeusuario.setObjectName("lineEdit_usuario_registrodeusuario")
        self.gridLayout.addWidget(self.lineEdit_usuario_registrodeusuario, 9, 0, 1, 1)
        self.lineEdit_nombre_registrodeusuario = QtWidgets.QLineEdit(parent=self.frame_registrodeusuarios)
        self.lineEdit_nombre_registrodeusuario.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_nombre_registrodeusuario.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_nombre_registrodeusuario.setObjectName("lineEdit_nombre_registrodeusuario")
        self.gridLayout.addWidget(self.lineEdit_nombre_registrodeusuario, 5, 0, 1, 2)
        self.lineEdit_cedula_registrodeusuario = QtWidgets.QLineEdit(parent=self.frame_registrodeusuarios)
        self.lineEdit_cedula_registrodeusuario.setMinimumSize(QtCore.QSize(30, 30))
        self.lineEdit_cedula_registrodeusuario.setText("")
        self.lineEdit_cedula_registrodeusuario.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_cedula_registrodeusuario.setObjectName("lineEdit_cedula_registrodeusuario")
        self.gridLayout.addWidget(self.lineEdit_cedula_registrodeusuario, 2, 0, 1, 2)
        self.pushButton_buscar_anadir_usu = QtWidgets.QPushButton(parent=self.frame_registrodeusuarios)
        self.pushButton_buscar_anadir_usu.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_buscar_anadir_usu.setObjectName("pushButton_buscar_anadir_usu")
        self.gridLayout.addWidget(self.pushButton_buscar_anadir_usu, 3, 0, 1, 2)
        self.lineEdit_apellido_registrodeusuario = QtWidgets.QLineEdit(parent=self.frame_registrodeusuarios)
        self.lineEdit_apellido_registrodeusuario.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_apellido_registrodeusuario.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_apellido_registrodeusuario.setObjectName("lineEdit_apellido_registrodeusuario")
        self.gridLayout.addWidget(self.lineEdit_apellido_registrodeusuario, 6, 0, 1, 2)
        self.horizontalLayout_4.addWidget(self.frame_registrodeusuarios)
        spacerItem10 = QtWidgets.QSpacerItem(261, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.stackedWidget.addWidget(self.page_anadir)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.frame_inferior)
        self.horizontalLayout_6.addWidget(self.frame_fondo)
        MainWindow_gestiondeusuarios.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_gestiondeusuarios)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_gestiondeusuarios)

    def retranslateUi(self, MainWindow_gestiondeusuarios):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_gestiondeusuarios.setWindowTitle(_translate("MainWindow_gestiondeusuarios", "Gestion de Usuarios"))
        self.pushButton_usuarios.setText(_translate("MainWindow_gestiondeusuarios", "Usuarios"))
        self.pushButton_anadir.setText(_translate("MainWindow_gestiondeusuarios", "Añadir"))
        self.pushButton_actualizar.setText(_translate("MainWindow_gestiondeusuarios", "Actualizar"))
        self.pushButton_eliminar.setText(_translate("MainWindow_gestiondeusuarios", "Eliminar"))
        self.pushButton_regresar_gestion.setText(_translate("MainWindow_gestiondeusuarios", "Regresar"))
        self.label_usuarios.setText(_translate("MainWindow_gestiondeusuarios", "Usuarios"))
        item = self.tableWidget_usuarios.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow_gestiondeusuarios", "Cedula"))
        item = self.tableWidget_usuarios.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow_gestiondeusuarios", "Nombre"))
        item = self.tableWidget_usuarios.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow_gestiondeusuarios", "Apellido"))
        item = self.tableWidget_usuarios.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow_gestiondeusuarios", "Telefono"))
        item = self.tableWidget_usuarios.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow_gestiondeusuarios", "Usuario"))
        item = self.tableWidget_usuarios.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow_gestiondeusuarios", "Clave"))
        item = self.tableWidget_usuarios.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow_gestiondeusuarios", "Permiso"))
        self.pushButton_refrescar.setText(_translate("MainWindow_gestiondeusuarios", "Actualizar"))
        self.label_actualizarusuarios.setText(_translate("MainWindow_gestiondeusuarios", "ACTUALIZAR DATOS DE USUARIO"))
        self.lineEdit_cedulabuscar_actualizarusuarios.setPlaceholderText(_translate("MainWindow_gestiondeusuarios", "Cédula"))
        self.pushButton_buscar_usu.setText(_translate("MainWindow_gestiondeusuarios", "Buscar"))
        self.lineEdit_nombre_actualizarusuarios.setPlaceholderText(_translate("MainWindow_gestiondeusuarios", "Nombre"))
        self.lineEdit_apellido_actualizarusuarios.setPlaceholderText(_translate("MainWindow_gestiondeusuarios", "Apellido"))
        self.lineEdit_telefono_actualizarusuarios.setPlaceholderText(_translate("MainWindow_gestiondeusuarios", "Teléfono"))
        self.lineEdit_usuario_actualizarusuarios.setPlaceholderText(_translate("MainWindow_gestiondeusuarios", "Usuario"))
        self.lineEdit_clave_actualizarusuarios.setPlaceholderText(_translate("MainWindow_gestiondeusuarios", "Clave"))
        self.comboBox_permiso_actualizarusuarios.setItemText(0, _translate("MainWindow_gestiondeusuarios", "Personal Base"))
        self.comboBox_permiso_actualizarusuarios.setItemText(1, _translate("MainWindow_gestiondeusuarios", "Supervisor"))
        self.pushButton_actualizarusuarios.setText(_translate("MainWindow_gestiondeusuarios", "Actualizar"))
        self.lineEdit_cedulabuscar_eliminar.setPlaceholderText(_translate("MainWindow_gestiondeusuarios", "Cédula"))
        self.pushButton_buscar_eliminar.setText(_translate("MainWindow_gestiondeusuarios", "Buscar"))
        item = self.tableWidget_eliminar.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow_gestiondeusuarios", "Cedula"))
        item = self.tableWidget_eliminar.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow_gestiondeusuarios", "Nombre"))
        item = self.tableWidget_eliminar.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow_gestiondeusuarios", "Apellido"))
        item = self.tableWidget_eliminar.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow_gestiondeusuarios", "Telefono"))
        item = self.tableWidget_eliminar.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow_gestiondeusuarios", "Usuario"))
        item = self.tableWidget_eliminar.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow_gestiondeusuarios", "Clave"))
        item = self.tableWidget_eliminar.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow_gestiondeusuarios", "Permiso"))
        self.pushButton_eliminar_eliminar.setText(_translate("MainWindow_gestiondeusuarios", "Eliminar"))
        self.label_eliminarusuarios.setText(_translate("MainWindow_gestiondeusuarios", "ELIMINAR USUARIO"))
        self.lineEdit_clave_registrodeusuario.setPlaceholderText(_translate("MainWindow_gestiondeusuarios", "Clave"))
        self.comboBox_permiso.setItemText(0, _translate("MainWindow_gestiondeusuarios", "Personal Base"))
        self.comboBox_permiso.setItemText(1, _translate("MainWindow_gestiondeusuarios", "Supervisor"))
        self.pushButton_limpiar_registrodeusuario.setText(_translate("MainWindow_gestiondeusuarios", "Limpiar"))
        self.pushButton_guardar_registrodeusuario.setText(_translate("MainWindow_gestiondeusuarios", "Guardar"))
        self.label_registrodeusuario.setText(_translate("MainWindow_gestiondeusuarios", "REGISTRO DE USUARIO"))
        self.lineEdit_telefono_registrodeusuario.setPlaceholderText(_translate("MainWindow_gestiondeusuarios", "Teléfono"))
        self.lineEdit_usuario_registrodeusuario.setPlaceholderText(_translate("MainWindow_gestiondeusuarios", "Usuario"))
        self.lineEdit_nombre_registrodeusuario.setPlaceholderText(_translate("MainWindow_gestiondeusuarios", "Nombre"))
        self.lineEdit_cedula_registrodeusuario.setPlaceholderText(_translate("MainWindow_gestiondeusuarios", "Cédula"))
        self.pushButton_buscar_anadir_usu.setText(_translate("MainWindow_gestiondeusuarios", "Buscar"))
        self.lineEdit_apellido_registrodeusuario.setPlaceholderText(_translate("MainWindow_gestiondeusuarios", "Apellido"))
