# Form implementation generated from reading ui file 'c:\Users\User\OneDrive\Tesis TSU Informatica\Sistema de control de inventario\Qt designer\10.Inventario.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_producto(object):
    def setupUi(self, MainWindow_producto):
        MainWindow_producto.setObjectName("MainWindow_producto")
        MainWindow_producto.resize(1102, 792)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow_producto)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_fondo = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_fondo.setStyleSheet("background-color: rgb(22, 22, 26);")
        self.frame_fondo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_fondo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_fondo.setObjectName("frame_fondo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_fondo)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superior = QtWidgets.QFrame(parent=self.frame_fondo)
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_superior.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:1, y2:0.5, stop:0 rgba(11, 38, 67, 184), stop: 1 rgba(150, 88, 240, 255));\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254); }\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:0.949, y2:0.545455, stop: 0 rgba(11, 38, 67, 184), stop:1 rgba(88, 240, 171, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_ajustesmanuales = QtWidgets.QPushButton(parent=self.frame_superior)
        self.pushButton_ajustesmanuales.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_ajustesmanuales.setObjectName("pushButton_ajustesmanuales")
        self.horizontalLayout.addWidget(self.pushButton_ajustesmanuales)
        self.pushButton_ingresarcompras = QtWidgets.QPushButton(parent=self.frame_superior)
        self.pushButton_ingresarcompras.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_ingresarcompras.setObjectName("pushButton_ingresarcompras")
        self.horizontalLayout.addWidget(self.pushButton_ingresarcompras)
        self.pushButton_ingresarventa = QtWidgets.QPushButton(parent=self.frame_superior)
        self.pushButton_ingresarventa.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_ingresarventa.setObjectName("pushButton_ingresarventa")
        self.horizontalLayout.addWidget(self.pushButton_ingresarventa)
        spacerItem = QtWidgets.QSpacerItem(207, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_salir_menu = QtWidgets.QPushButton(parent=self.frame_superior)
        self.pushButton_salir_menu.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_salir_menu.setStyleSheet("QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.727273 rgba(142, 19, 16, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}")
        self.pushButton_salir_menu.setObjectName("pushButton_salir_menu")
        self.horizontalLayout.addWidget(self.pushButton_salir_menu)
        self.verticalLayout_2.addWidget(self.frame_superior)
        self.frame_inferior = QtWidgets.QFrame(parent=self.frame_fondo)
        self.frame_inferior.setStyleSheet("\n"
"\n"
"QLabel {\n"
"background-color: #000000ff;\n"
"}\n"
"\n"
"QTableWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    gridline-color: rgb(206, 0, 55);\n"
"font-size: 12px;\n"
"color: #000000;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"\n"
"background-color: rgb(0, 206, 151);\n"
"\n"
"border: 1px solid rgb(0, 0, 0);\n"
"\n"
"font-size: 12pt;\n"
"\n"
"}\n"
"\n"
"I\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"border: 1px solid rgb(0, 206, 151);\n"
"\n"
"}")
        self.frame_inferior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_inferior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_inferior.setObjectName("frame_inferior")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_inferior)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_inferior)
        self.stackedWidget.setMinimumSize(QtCore.QSize(1080, 720))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_ajuste_manual = QtWidgets.QWidget()
        self.page_ajuste_manual.setMinimumSize(QtCore.QSize(1080, 720))
        self.page_ajuste_manual.setObjectName("page_ajuste_manual")
        self.gridLayout = QtWidgets.QGridLayout(self.page_ajuste_manual)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_busquedadeusuarios_4 = QtWidgets.QFrame(parent=self.page_ajuste_manual)
        self.frame_busquedadeusuarios_4.setMinimumSize(QtCore.QSize(369, 606))
        self.frame_busquedadeusuarios_4.setMaximumSize(QtCore.QSize(369, 1000))
        self.frame_busquedadeusuarios_4.setStyleSheet("QLineEdit{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"SansSerif\";\n"
"color: rgb(255, 255, 254);\n"
"border: 2px solid rgb(114, 117, 126);}\n"
"\n"
"QLineEdit:hover{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"border: 2px solid rgb(44, 182, 125); }\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(1, 1, 1);\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"border: 2px solid rgb(127, 90, 240);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:1, y2:0.5, stop:0 rgba(11, 38, 67, 184), stop: 1 rgba(150, 88, 240, 255));\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254); }\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:0.949, y2:0.545455, stop: 0 rgba(11, 38, 67, 184), stop:1 rgba(88, 240, 171, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"SansSerif\";\n"
"color: rgb(255, 255, 254);\n"
"border: 2px solid rgb(114, 117, 126);}\n"
"\n"
"QComboBox:hover{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"border: 2px solid rgb(44, 182, 125); }\n"
"\n"
"QFrame{\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(84, 135, 255)\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.frame_busquedadeusuarios_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_busquedadeusuarios_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_busquedadeusuarios_4.setObjectName("frame_busquedadeusuarios_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_busquedadeusuarios_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_imagen_producto = QtWidgets.QFrame(parent=self.frame_busquedadeusuarios_4)
        self.frame_imagen_producto.setMinimumSize(QtCore.QSize(347, 300))
        self.frame_imagen_producto.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_imagen_producto.setStyleSheet("border-image: url(:/Producto/sticker-png-delivery-icon-product-icon.png);\n"
"background-color: rgb(255, 255, 255);")
        self.frame_imagen_producto.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_imagen_producto.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_imagen_producto.setObjectName("frame_imagen_producto")
        self.gridLayout_2.addWidget(self.frame_imagen_producto, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 4, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.label_actualizar_cantd = QtWidgets.QLabel(parent=self.frame_busquedadeusuarios_4)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        self.label_actualizar_cantd.setFont(font)
        self.label_actualizar_cantd.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 0px;\n"
"\n"
"border:0px;")
        self.label_actualizar_cantd.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_actualizar_cantd.setObjectName("label_actualizar_cantd")
        self.horizontalLayout_14.addWidget(self.label_actualizar_cantd)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        self.lineEdit_descrip_prod = QtWidgets.QLineEdit(parent=self.frame_busquedadeusuarios_4)
        self.lineEdit_descrip_prod.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_descrip_prod.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_descrip_prod.setObjectName("lineEdit_descrip_prod")
        self.gridLayout_2.addWidget(self.lineEdit_descrip_prod, 8, 0, 1, 1)
        self.lineEdit_cant_prod = QtWidgets.QLineEdit(parent=self.frame_busquedadeusuarios_4)
        self.lineEdit_cant_prod.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_cant_prod.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_cant_prod.setObjectName("lineEdit_cant_prod")
        self.gridLayout_2.addWidget(self.lineEdit_cant_prod, 9, 0, 1, 1)
        self.lineEdit_sku_buscar = QtWidgets.QLineEdit(parent=self.frame_busquedadeusuarios_4)
        self.lineEdit_sku_buscar.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_sku_buscar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_sku_buscar.setObjectName("lineEdit_sku_buscar")
        self.gridLayout_2.addWidget(self.lineEdit_sku_buscar, 5, 0, 1, 1)
        self.pushButton_actualizar_cant = QtWidgets.QPushButton(parent=self.frame_busquedadeusuarios_4)
        self.pushButton_actualizar_cant.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_actualizar_cant.setObjectName("pushButton_actualizar_cant")
        self.gridLayout_2.addWidget(self.pushButton_actualizar_cant, 10, 0, 1, 1)
        self.pushButton_buscar_sku = QtWidgets.QPushButton(parent=self.frame_busquedadeusuarios_4)
        self.pushButton_buscar_sku.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_buscar_sku.setObjectName("pushButton_buscar_sku")
        self.gridLayout_2.addWidget(self.pushButton_buscar_sku, 6, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 7, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 2, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_busquedadeusuarios_4, 1, 1, 2, 2)
        spacerItem7 = QtWidgets.QSpacerItem(337, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 3, 1, 1)
        self.label_stock = QtWidgets.QLabel(parent=self.page_ajuste_manual)
        self.label_stock.setMinimumSize(QtCore.QSize(0, 42))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        self.label_stock.setFont(font)
        self.label_stock.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_stock.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_stock.setObjectName("label_stock")
        self.gridLayout.addWidget(self.label_stock, 0, 0, 1, 5)
        spacerItem8 = QtWidgets.QSpacerItem(335, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem8, 1, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem9)
        self.gridLayout.addLayout(self.horizontalLayout_13, 3, 0, 1, 4)
        self.stackedWidget.addWidget(self.page_ajuste_manual)
        self.page_compras = QtWidgets.QWidget()
        self.page_compras.setStyleSheet("")
        self.page_compras.setObjectName("page_compras")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_compras)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem10 = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_4.addItem(spacerItem10, 1, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(337, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_4.addItem(spacerItem11, 2, 2, 1, 1)
        self.frame_busquedadeusuarios_6 = QtWidgets.QFrame(parent=self.page_compras)
        self.frame_busquedadeusuarios_6.setMinimumSize(QtCore.QSize(369, 606))
        self.frame_busquedadeusuarios_6.setMaximumSize(QtCore.QSize(369, 670))
        self.frame_busquedadeusuarios_6.setStyleSheet("QLineEdit{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"SansSerif\";\n"
"color: rgb(255, 255, 254);\n"
"border: 2px solid rgb(114, 117, 126);}\n"
"\n"
"QLineEdit:hover{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"border: 2px solid rgb(44, 182, 125); }\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(1, 1, 1);\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"border: 2px solid rgb(127, 90, 240);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:1, y2:0.5, stop:0 rgba(11, 38, 67, 184), stop: 1 rgba(150, 88, 240, 255));\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254); }\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:0.949, y2:0.545455, stop: 0 rgba(11, 38, 67, 184), stop:1 rgba(88, 240, 171, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"SansSerif\";\n"
"color: rgb(255, 255, 254);\n"
"border: 2px solid rgb(114, 117, 126);}\n"
"\n"
"QComboBox:hover{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"border: 2px solid rgb(44, 182, 125); }\n"
"\n"
"QFrame{\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(84, 135, 255)\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.frame_busquedadeusuarios_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_busquedadeusuarios_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_busquedadeusuarios_6.setObjectName("frame_busquedadeusuarios_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_busquedadeusuarios_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_ingresarcompra = QtWidgets.QLabel(parent=self.frame_busquedadeusuarios_6)
        self.label_ingresarcompra.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        self.label_ingresarcompra.setFont(font)
        self.label_ingresarcompra.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 0px;\n"
"\n"
"border:0px;")
        self.label_ingresarcompra.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_ingresarcompra.setObjectName("label_ingresarcompra")
        self.verticalLayout_5.addWidget(self.label_ingresarcompra)
        self.lineEdit_sku_ingresarcompra = QtWidgets.QLineEdit(parent=self.frame_busquedadeusuarios_6)
        self.lineEdit_sku_ingresarcompra.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_sku_ingresarcompra.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_sku_ingresarcompra.setObjectName("lineEdit_sku_ingresarcompra")
        self.verticalLayout_5.addWidget(self.lineEdit_sku_ingresarcompra)
        self.pushButton_buscar_ingresarcompra = QtWidgets.QPushButton(parent=self.frame_busquedadeusuarios_6)
        self.pushButton_buscar_ingresarcompra.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_buscar_ingresarcompra.setObjectName("pushButton_buscar_ingresarcompra")
        self.verticalLayout_5.addWidget(self.pushButton_buscar_ingresarcompra)
        self.lineEdit_descripicion_ingresarcompra = QtWidgets.QLineEdit(parent=self.frame_busquedadeusuarios_6)
        self.lineEdit_descripicion_ingresarcompra.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_descripicion_ingresarcompra.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_descripicion_ingresarcompra.setObjectName("lineEdit_descripicion_ingresarcompra")
        self.verticalLayout_5.addWidget(self.lineEdit_descripicion_ingresarcompra)
        self.lineEdit_fecha_ingresarcompra = QtWidgets.QLineEdit(parent=self.frame_busquedadeusuarios_6)
        self.lineEdit_fecha_ingresarcompra.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_fecha_ingresarcompra.setMaxLength(10)
        self.lineEdit_fecha_ingresarcompra.setFrame(True)
        self.lineEdit_fecha_ingresarcompra.setCursorPosition(0)
        self.lineEdit_fecha_ingresarcompra.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_fecha_ingresarcompra.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_fecha_ingresarcompra.setObjectName("lineEdit_fecha_ingresarcompra")
        self.verticalLayout_5.addWidget(self.lineEdit_fecha_ingresarcompra)
        self.lineEdit_cod_ingresarcompra = QtWidgets.QLineEdit(parent=self.frame_busquedadeusuarios_6)
        self.lineEdit_cod_ingresarcompra.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_cod_ingresarcompra.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_cod_ingresarcompra.setObjectName("lineEdit_cod_ingresarcompra")
        self.verticalLayout_5.addWidget(self.lineEdit_cod_ingresarcompra)
        self.lineEdit_cant_ingresarcompra = QtWidgets.QLineEdit(parent=self.frame_busquedadeusuarios_6)
        self.lineEdit_cant_ingresarcompra.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_cant_ingresarcompra.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_cant_ingresarcompra.setObjectName("lineEdit_cant_ingresarcompra")
        self.verticalLayout_5.addWidget(self.lineEdit_cant_ingresarcompra)
        self.pushButton_enviar_compra = QtWidgets.QPushButton(parent=self.frame_busquedadeusuarios_6)
        self.pushButton_enviar_compra.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_enviar_compra.setObjectName("pushButton_enviar_compra")
        self.verticalLayout_5.addWidget(self.pushButton_enviar_compra)
        self.pushButton_limpiar_campos_compras = QtWidgets.QPushButton(parent=self.frame_busquedadeusuarios_6)
        self.pushButton_limpiar_campos_compras.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_limpiar_campos_compras.setStyleSheet("QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.727273 rgba(142, 19, 16, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}")
        self.pushButton_limpiar_campos_compras.setObjectName("pushButton_limpiar_campos_compras")
        self.verticalLayout_5.addWidget(self.pushButton_limpiar_campos_compras)
        self.gridLayout_4.addWidget(self.frame_busquedadeusuarios_6, 1, 1, 3, 1)
        self.label_stock_danados = QtWidgets.QLabel(parent=self.page_compras)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        self.label_stock_danados.setFont(font)
        self.label_stock_danados.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_stock_danados.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_stock_danados.setObjectName("label_stock_danados")
        self.gridLayout_4.addWidget(self.label_stock_danados, 0, 0, 1, 3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem12)
        self.gridLayout_4.addLayout(self.horizontalLayout_10, 4, 0, 1, 3)
        self.stackedWidget.addWidget(self.page_compras)
        self.page_ventas = QtWidgets.QWidget()
        self.page_ventas.setStyleSheet("")
        self.page_ventas.setObjectName("page_ventas")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_ventas)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem13 = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem13, 1, 0, 1, 1)
        self.frame_busquedadeusuarios_5 = QtWidgets.QFrame(parent=self.page_ventas)
        self.frame_busquedadeusuarios_5.setMinimumSize(QtCore.QSize(369, 606))
        self.frame_busquedadeusuarios_5.setMaximumSize(QtCore.QSize(369, 670))
        self.frame_busquedadeusuarios_5.setStyleSheet("QLineEdit{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"SansSerif\";\n"
"color: rgb(255, 255, 254);\n"
"border: 2px solid rgb(114, 117, 126);}\n"
"\n"
"QLineEdit:hover{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"border: 2px solid rgb(44, 182, 125); }\n"
"\n"
"QLineEdit:focus {\n"
"background-color: rgb(1, 1, 1);\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"border: 2px solid rgb(127, 90, 240);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:1, y2:0.5, stop:0 rgba(11, 38, 67, 184), stop: 1 rgba(150, 88, 240, 255));\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254); }\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.562273, x2:0.949, y2:0.545455, stop: 0 rgba(11, 38, 67, 184), stop:1 rgba(88, 240, 171, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"SansSerif\";\n"
"color: rgb(255, 255, 254);\n"
"border: 2px solid rgb(114, 117, 126);}\n"
"\n"
"QComboBox:hover{\n"
"background-color: rgb(22, 22, 26);\n"
"border-radius: 10px;\n"
"font: 12pt \"Sans Serif\";\n"
"border: 2px solid rgb(44, 182, 125); }\n"
"\n"
"QFrame{\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(84, 135, 255)\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.frame_busquedadeusuarios_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_busquedadeusuarios_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_busquedadeusuarios_5.setObjectName("frame_busquedadeusuarios_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_busquedadeusuarios_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_ingresarventa = QtWidgets.QLabel(parent=self.frame_busquedadeusuarios_5)
        self.label_ingresarventa.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        self.label_ingresarventa.setFont(font)
        self.label_ingresarventa.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 0px;\n"
"\n"
"border:0px;")
        self.label_ingresarventa.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_ingresarventa.setObjectName("label_ingresarventa")
        self.verticalLayout_4.addWidget(self.label_ingresarventa)
        self.lineEdit_sku_ingresarventa = QtWidgets.QLineEdit(parent=self.frame_busquedadeusuarios_5)
        self.lineEdit_sku_ingresarventa.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_sku_ingresarventa.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_sku_ingresarventa.setObjectName("lineEdit_sku_ingresarventa")
        self.verticalLayout_4.addWidget(self.lineEdit_sku_ingresarventa)
        self.pushButton_buscar_ingresarventa = QtWidgets.QPushButton(parent=self.frame_busquedadeusuarios_5)
        self.pushButton_buscar_ingresarventa.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_buscar_ingresarventa.setObjectName("pushButton_buscar_ingresarventa")
        self.verticalLayout_4.addWidget(self.pushButton_buscar_ingresarventa)
        self.lineEdit_descripicion_ingresarventa = QtWidgets.QLineEdit(parent=self.frame_busquedadeusuarios_5)
        self.lineEdit_descripicion_ingresarventa.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_descripicion_ingresarventa.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_descripicion_ingresarventa.setObjectName("lineEdit_descripicion_ingresarventa")
        self.verticalLayout_4.addWidget(self.lineEdit_descripicion_ingresarventa)
        self.lineEdit_fecha_ingresarventa = QtWidgets.QLineEdit(parent=self.frame_busquedadeusuarios_5)
        self.lineEdit_fecha_ingresarventa.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_fecha_ingresarventa.setMaxLength(10)
        self.lineEdit_fecha_ingresarventa.setFrame(True)
        self.lineEdit_fecha_ingresarventa.setCursorPosition(0)
        self.lineEdit_fecha_ingresarventa.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_fecha_ingresarventa.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_fecha_ingresarventa.setObjectName("lineEdit_fecha_ingresarventa")
        self.verticalLayout_4.addWidget(self.lineEdit_fecha_ingresarventa)
        self.lineEdit_cod_ingresarventa = QtWidgets.QLineEdit(parent=self.frame_busquedadeusuarios_5)
        self.lineEdit_cod_ingresarventa.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_cod_ingresarventa.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_cod_ingresarventa.setObjectName("lineEdit_cod_ingresarventa")
        self.verticalLayout_4.addWidget(self.lineEdit_cod_ingresarventa)
        self.lineEdit_cant_ingresarventa = QtWidgets.QLineEdit(parent=self.frame_busquedadeusuarios_5)
        self.lineEdit_cant_ingresarventa.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_cant_ingresarventa.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_cant_ingresarventa.setObjectName("lineEdit_cant_ingresarventa")
        self.verticalLayout_4.addWidget(self.lineEdit_cant_ingresarventa)
        self.pushButton_enviar = QtWidgets.QPushButton(parent=self.frame_busquedadeusuarios_5)
        self.pushButton_enviar.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_enviar.setObjectName("pushButton_enviar")
        self.verticalLayout_4.addWidget(self.pushButton_enviar)
        self.pushButton_limpiar = QtWidgets.QPushButton(parent=self.frame_busquedadeusuarios_5)
        self.pushButton_limpiar.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_limpiar.setStyleSheet("QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.727273 rgba(142, 19, 16, 255));\n"
"border-radius:10px;\n"
"font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 255, 254);\n"
"}")
        self.pushButton_limpiar.setObjectName("pushButton_limpiar")
        self.verticalLayout_4.addWidget(self.pushButton_limpiar)
        self.gridLayout_3.addWidget(self.frame_busquedadeusuarios_5, 1, 1, 2, 1)
        spacerItem14 = QtWidgets.QSpacerItem(337, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem14, 2, 2, 1, 1)
        self.label_stock_vencidos = QtWidgets.QLabel(parent=self.page_ventas)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        self.label_stock_vencidos.setFont(font)
        self.label_stock_vencidos.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_stock_vencidos.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_stock_vencidos.setObjectName("label_stock_vencidos")
        self.gridLayout_3.addWidget(self.label_stock_vencidos, 0, 0, 1, 3)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem15)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 3, 0, 1, 3)
        self.stackedWidget.addWidget(self.page_ventas)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.frame_inferior)
        self.verticalLayout_3.addWidget(self.frame_fondo)
        MainWindow_producto.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_producto)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_producto)

    def retranslateUi(self, MainWindow_producto):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_producto.setWindowTitle(_translate("MainWindow_producto", "Menu Principal"))
        self.pushButton_ajustesmanuales.setText(_translate("MainWindow_producto", "Ajustes manuales"))
        self.pushButton_ingresarcompras.setText(_translate("MainWindow_producto", "Compras"))
        self.pushButton_ingresarventa.setText(_translate("MainWindow_producto", "Ventas"))
        self.pushButton_salir_menu.setText(_translate("MainWindow_producto", "Salir"))
        self.frame_imagen_producto.setWhatsThis(_translate("MainWindow_producto", "<html><head/><body><p><img src=\":/Producto/sticker-png-delivery-icon-product-icon.png\"/></p></body></html>"))
        self.label_actualizar_cantd.setText(_translate("MainWindow_producto", "AJUSTE MANUAL DE PRODUCTOS"))
        self.lineEdit_descrip_prod.setPlaceholderText(_translate("MainWindow_producto", "Descripción"))
        self.lineEdit_cant_prod.setPlaceholderText(_translate("MainWindow_producto", "Cantidad"))
        self.lineEdit_sku_buscar.setPlaceholderText(_translate("MainWindow_producto", "SKU"))
        self.pushButton_actualizar_cant.setText(_translate("MainWindow_producto", "Actualizar"))
        self.pushButton_buscar_sku.setText(_translate("MainWindow_producto", "Buscar"))
        self.label_stock.setText(_translate("MainWindow_producto", "AJUSTE MANUAL"))
        self.label_ingresarcompra.setText(_translate("MainWindow_producto", "INGRESAR COMPRA"))
        self.lineEdit_sku_ingresarcompra.setPlaceholderText(_translate("MainWindow_producto", "SKU"))
        self.pushButton_buscar_ingresarcompra.setText(_translate("MainWindow_producto", "Buscar"))
        self.lineEdit_descripicion_ingresarcompra.setPlaceholderText(_translate("MainWindow_producto", "Descripción"))
        self.lineEdit_fecha_ingresarcompra.setInputMask(_translate("MainWindow_producto", "99-99-9999;_"))
        self.lineEdit_fecha_ingresarcompra.setText(_translate("MainWindow_producto", "--", "DD/MM/AA"))
        self.lineEdit_fecha_ingresarcompra.setPlaceholderText(_translate("MainWindow_producto", "DD/MM/AA", "DD/MM/AA"))
        self.lineEdit_cod_ingresarcompra.setPlaceholderText(_translate("MainWindow_producto", "Codigo de Producto"))
        self.lineEdit_cant_ingresarcompra.setPlaceholderText(_translate("MainWindow_producto", "Cantidad"))
        self.pushButton_enviar_compra.setText(_translate("MainWindow_producto", "Enviar"))
        self.pushButton_limpiar_campos_compras.setText(_translate("MainWindow_producto", "Limpiar"))
        self.label_stock_danados.setText(_translate("MainWindow_producto", "COMPRAS"))
        self.label_ingresarventa.setText(_translate("MainWindow_producto", "INGRESAR VENTA"))
        self.lineEdit_sku_ingresarventa.setPlaceholderText(_translate("MainWindow_producto", "SKU"))
        self.pushButton_buscar_ingresarventa.setText(_translate("MainWindow_producto", "Buscar"))
        self.lineEdit_descripicion_ingresarventa.setPlaceholderText(_translate("MainWindow_producto", "Descripción"))
        self.lineEdit_fecha_ingresarventa.setInputMask(_translate("MainWindow_producto", "99-99-9999;_"))
        self.lineEdit_fecha_ingresarventa.setText(_translate("MainWindow_producto", "--", "DD/MM/AA"))
        self.lineEdit_fecha_ingresarventa.setPlaceholderText(_translate("MainWindow_producto", "DD/MM/AA", "DD/MM/AA"))
        self.lineEdit_cod_ingresarventa.setPlaceholderText(_translate("MainWindow_producto", "Codigo de Producto"))
        self.lineEdit_cant_ingresarventa.setPlaceholderText(_translate("MainWindow_producto", "Cantidad"))
        self.pushButton_enviar.setText(_translate("MainWindow_producto", "Enviar"))
        self.pushButton_limpiar.setText(_translate("MainWindow_producto", "Limpiar"))
        self.label_stock_vencidos.setText(_translate("MainWindow_producto", "VENTAS"))
